# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_testpractice.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1031, 731)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 991, 501))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setDocumentTitle("")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 181, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(200, 580, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 580, 131, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 670, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(400, 660, 151, 41))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(780, 670, 101, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 580, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(860, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 550, 111, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(530, 610, 111, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.slot_check)
        self.pushButton_3.clicked.connect(Form.slot_read)
        self.pushButton_4.clicked.connect(Form.slot_testnext)
        self.pushButton_2.clicked.connect(Form.slot_fileopen)
        self.pushButton_5.clicked.connect(Form.slot_exit)
        self.pushButton_6.clicked.connect(Form.slot_oldfile)
        self.pushButton_7.clicked.connect(Form.slot_back)
        self.pushButton_8.clicked.connect(Form.slot_yes)
        self.pushButton_9.clicked.connect(Form.slot_no)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数学题训练助手"))
        self.label_2.setText(_translate("Form", "试题"))
        self.pushButton.setText(_translate("Form", "核对答案"))
        self.pushButton_3.setText(_translate("Form", "查看讲解"))
        self.pushButton_4.setText(_translate("Form", "开始答题\\下一题"))
        self.pushButton_2.setText(_translate("Form", "打开新练习"))
        self.pushButton_5.setText(_translate("Form", "保存记录退出"))
        self.pushButton_6.setText(_translate("Form", "打开上次练习"))
        self.pushButton_7.setText(_translate("Form", "返回上一题"))
        self.pushButton_8.setText(_translate("Form", "做对了点这里"))
        self.pushButton_9.setText(_translate("Form", "做错了点这里"))


